#!/bin/bash

### Script below ###
module load shared tools
module load tools
module load anaconda3/4.4.0
module load java/1.8.0-openjdk
module load bowtie2/2.3.4.1 python36 samtools/1.9 htslib/1.9 gcc perl pigz/2.3.4
module load bismark/0.22.1 fastqc/0.11.8 trim_galore/0.6.4 adapterremoval/2.2.4

# change the file location accordingly
raw_data={dir_with_raw_data}
out_direc={dir_for_output}
ref_direc={dir_for_salmon_ref_genome}

for SAMPLE in {SAMPLE NAMES}
do

        mkdir -p $out_direc/2_fastqc_before/$SAMPLE
        mkdir -p $out_direc/3_adapterremoval/$SAMPLE
        mkdir -p $out_direc/4_fastqc_after/$SAMPLE
        mkdir -p $out_direc/5_bismark/$SAMPLE

        # fastqc - before trimming (add "-t 4" later)
        cd $raw_data/$SAMPLE
        file=`ls -a *fq.gz | sort`
        fastqc $file -t 10 -o $out_direc/2_fastqc_before/$SAMPLE

        # AdapterRemoval
        cd $out_direc/3_adapterremoval/$SAMPLE
        AdapterRemoval --threads 10 --file1 $raw_data/$SAMPLE/*_1.fq.gz --file2 $raw_data/$SAMPLE/*_2.fq.gz --basename $SAMPLE --trimns --trimqualities --minlength 25 --gzip --settings $SAMPLE.settings

        # fastqc - after trimming
        cd $out_direc/3_adapterremoval/$SAMPLE
        file=`ls -a $SAMPLE.pair*.gz | sort`
        fastqc $file -t 10 -o $out_direc/4_fastqc_after/$SAMPLE

        # bismark
        cd $out_direc/3_adapterremoval/$SAMPLE
        bismark --multi 10 --genome $ref_direc --output_dir $out_direc/5_bismark/$SAMPLE -1 $SAMPLE.pair1.truncated.gz -2 $SAMPLE.pair2.truncated.gz

        # deduplication
        cd $out_direc/5_bismark/$SAMPLE
        deduplicate_bismark --paired --bam *bam --multi 10

        # methylation extraction (excluded "--counts"; excluded "--multi")
        cd $out_direc/5_bismark/$SAMPLE
        bismark_methylation_extractor -p --gzip --bedGraph --scaffolds --buffer_size 85% --ignore_r2 3 --multi 10 -o out_direc --genome_folder $ref_direc $SAMPLE*.deduplicated.bam

done
